version: '3.9'
name: flatnotes
# flatnotes stack

# Page: https://github.com/dullage/flatnotes/wiki
# Dckr: https://github.com/dullage/flatnotes#example-docker-compose
# Code: https://github.com/dullage/flatnotes

# A self-hosted, database-less note taking web
# app that utilises a flat folder of markdown
# files for storage.

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: dullage/flatnotes:${FLATNOTES_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${FLATNOTES_UID:-1000}
      PGID: ${FLATNOTES_GID:-1000}
      FLATNOTES_AUTH_TYPE: ${FLATNOTES_AUTH:-password}
      FLATNOTES_USERNAME: ${FLATNOTES_USER:-user}
      FLATNOTES_PASSWORD: ${FLATNOTES_PASS:?Set flatnotes user password}
      FLATNOTES_SECRET_KEY: ${FLATNOTES_SECRET:?Set flatnotes secret key}
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
