name: ${STACK_NAME:-wallabag}

include:
  - ../fragments/network-default.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-smtp.yml
  - ../fragments/network-outgoing.yml
  - ../fragments/service-valkey-persistent.yml
  - ../fragments/service-mariadb.yml

services:

  wallabag:
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    image: wallabag/wallabag:${WALLABAG_TAG:-latest}
    depends_on:
      mariadb:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file: stack.env
    networks:
      - default
      - proxy
      - smtp
      - outgoing
    volumes:
      - ${ASSETS_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/assets}:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
