name: wallabag

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:${WALLABAG_MARIADB_TAG:-11}
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MARIADB_MYSQL_LOCALHOST_USER
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 3s

  kv:
    container_name: ${COMPOSE_PROJECT_NAME}-kv
    image: valkey/valkey:${WALLABAG_VALKEY_TAG:-alpine}
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 20s
      timeout: 3s

  wallabag:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: wallabag/wallabag:${WALLABAG_TAG:-latest}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      kv:
        condition: service_healthy
    env_file: stack.env
    networks:
      - default
      - proxy
      - smtp
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/assets:/var/www/wallabag/web/assets/images
      - /etc/${COMPOSE_PROJECT_NAME}:/var/www/wallabag/app/config
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      timeout: 10s
      start_interval: 10s
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  default:
    internal: true
  proxy:
    external: true
  smtp:
    external: true
