name: ${STACK_NAME:-wallabag}

include:
  - ../fragments/network-default.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-smtp.yml
  - ../fragments/network-outgoing.yml

services:

  db:
    extends:
      file: ../fragments/services.yml
      service: mariadb

  kv:
    extends:
      file: ../fragments/services.yml
      service: valkey-persistent

  wallabag:
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    image: wallabag/wallabag:${WALLABAG_TAG:-latest}
    depends_on:
      db:
        condition: service_healthy
      kv:
        condition: service_healthy
    env_file: stack.env
    networks:
      - default
      - proxy
      - smtp
      - outgoing
    volumes:
      - ${ASSETS_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/assets}:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
