version: '3.9'
name: postal
# Postal stack

# Page: https://postalserver.io/
# Dckr: https://github.com/postalserver/postal/blob/main/docker-compose.yml
# Code: https://github.com/postalserver/postal

# A complete and fully featured mail server for use
# by websites & web servers. Think Sendgrid, Mailgun
# or Postmark but open source and ready for you to
# run on your own servers.

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ghcr.io/postalserver/postal:${POSTAL_TAG:-stable}
    depends_on:
      - mariadb
    entrypoint: ["/docker-entrypoint.sh"]
    restart: unless-stopped
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/config
      - /srv/${COMPOSE_PROJECT_NAME}/app/dkim:/dkim
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - default
      - proxy
      - smtp
      - exposed
    env_file: stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5000"

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: mariadb:${POSTAL_MARIADB_TAG:-latest}
    restart: always
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql
    networks:
      - default
    environment:
      - MARIADB_DATABASE
      - MARIADB_ALLOW_EMPTY_PASSWORD
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD

networks:
  default:
    internal: true
  proxy:
    external: true
  smtp:
    external: true
  exposed:
    external: true
