name: leantime

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: leantime/leantime:${LEANTIME_TAG:-latest}
    restart: unless-stopped
    env_file: stack.env
    networks:
      - default
      - proxy
      - smtp
      - exposed
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/public:/var/www/html/public/userfiles
      - /srv/${COMPOSE_PROJECT_NAME}/private:/var/www/html/userfiles
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER?Certificate resolver is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

  leantime-db:
    image: mysql:${LEANTIME_DB_TAG:-8.0}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    restart: unless-stopped
    env_file: stack.env
    networks:
      - default
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql

networks:
  default:
    internal: true
  proxy:
    external: true
  smtp:
    external: true
  exposed:
    external: true
