name: docker-mailserver

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: mail.${COMPOSE_DOMAIN}
    image: ghcr.io/docker-mailserver/docker-mailserver:${DOCKER_MAILSERVER_TAG:-latest}
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/data:/var/mail
      - /srv/${COMPOSE_PROJECT_NAME}/state:/var/mail-state
      - /var/log/${COMPOSE_PROJECT_NAME}:/var/log/mail
      - /etc/${COMPOSE_PROJECT_NAME}:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      proxy:
        priority: 10
      smtp:
        priority: 30
        aliases:
          - mail.${COMPOSE_DOMAIN}
          - ${COMPOSE_PROJECT_NAME}
          - mailserver
      exposed:
        priority: 20
    env_file: stack.env
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=11334"

networks:
  smtp:
    external: true
  exposed:
    external: true
  proxy:
    external: true
