name: maker-management-platform

services:

  agent:
    image: ghcr.io/maker-management-platform/agent:${MMP_AGENT_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-agent
    hostname: ${COMPOSE_PROJECT_NAME}-agent
    volumes:
      - /srv/octoprint/octoprint/uploads:/library # should contain your project library
      - /srv/${COMPOSE_PROJECT_NAME}:/data # will contain config and state files
    ports:
      - 8000:8000 # currently required for your slicer integration, looking for a workaround
    restart: unless-stopped
    networks:
      - default
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-agent.rule=Host(`${COMPOSE_PROJECT_NAME}-agent.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-agent.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-agent.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-agent.service=${COMPOSE_PROJECT_NAME}-agent"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-agent.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-agent.loadbalancer.server.port=8000"

  ui:
    image: ghcr.io/maker-management-platform/mmp-ui:${MMP_UI_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-ui
    hostname: ${COMPOSE_PROJECT_NAME}-ui
    environment:
      - "AGENT_ADDRESS=${COMPOSE_PROJECT_NAME}-agent:8000" #local address for the agent
    restart: unless-stopped
    networks:
      - default
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ui.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ui.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ui.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ui.service=${COMPOSE_PROJECT_NAME}-ui"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ui.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-ui.loadbalancer.server.port=8081"

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
