name: proxitok

services:

  proxitok:
    image: ghcr.io/pablouser1/proxitok:${PROXITOK_TAG:-master}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=${COMPOSE_PROJECT_NAME}-kv
      - REDIS_PORT=6379
      - API_CHROMEDRIVER=http://proxitok-chromedriver:9515
    tmpfs:
      - /cache:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    depends_on:
      - valkey
      - chromedriver
    networks:
      - default
      - proxy
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"
      - "io.containers.autoupdate=registry"

  valkey:
    extends:
      file: ../fragments/services.yml
      service: valkey-ephemeral
    init: true
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    labels:
      - "io.containers.autoupdate=registry"

  chromedriver:
    container_name: ${COMPOSE_PROJECT_NAME}-chromedriver
    image: zenika/alpine-chrome:${PROXITOK_CHROMEDRIVER_TAG:-with-chromedriver}
    extends:
      file: ../fragments/services.yml
      service: service-sub
    init: true
    shm_size: 1g
    security_opt:
      - seccomp:${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}/chrome.json
    labels:
      - "io.containers.autoupdate=registry"

networks:
  default:
    internal: true
  proxy:
    external: true
  exposed:
    external: true
