name: noisedash

services:

  noisedash:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: noisedash/noisedash:${NOISEDASH_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
      - exposed
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/var/noisedash/db
      - /var/${COMPOSE_PROJECT_NAME}:/var/noisedash/samples
      - /etc/${COMPOSE_PROJECT_NAME}:/var/noisedash/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=1432"

networks:
  proxy:
    external: true
  exposed:
    external: true
