name: whoogle

services:

  araa:
    image: benbusby/whoogle-search:${WHOOGLE_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    environment:
      WHOOGLE_ALT_TW: ${TWITTER_ALT-nitter.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_YT: ${YOUTUBE_ALT-invidious.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_IG: ${INSTAGRAM_ALT-bibliogram.${COMPOSE_DOMAIN}/u}
      WHOOGLE_ALT_RD: ${REDDIT_ALT-libreddit.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_MD: ${MEDIUM_ALT-scribe.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_TL: ${TRANSLATE_ALT-lingva.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_IMG: ${IMGUR_ALT-rimgo.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_WIKI: ${WIKIPEDIA_ALT-wikiless.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_IMDB: ${IMDB_ALT-libremdb.${COMPOSE_DOMAIN}}
      WHOOGLE_ALT_QUORA: ${QUORA_ALT-quetre.${COMPOSE_DOMAIN}}
      WHOOGLE_UPDATE_CHECK: "0"
      WHOOGLE_CONFIG_VIEW_IMAGE: "1"
      WHOOGLE_CONFIG_URL: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}
      WHOOGLE_REDIRECTS: ${WHOOGLE_REDIRECTS}
    networks:
      - exposed
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true
  exposed:
    external: true
