name: aria2

services:

  aria2-pro:
    image: p3terx/aria2-pro:${ARIA2_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-hc
    hostname: ${COMPOSE_PROJECT_NAME}
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - UMASK_SET=${UMASK:-022}
      - RPC_SECRET=${SECRET:?No RPC secret set}
      - RPC_PORT=${RPC_PORT:-6800}
      - LISTEN_PORT=${BT_LISTEN_PORT:-6881-6999}
      - DISK_CACHE=${CACHE:-64M}
      - IPV6_MODE=${IPV6:-false}
      - UPDATE_TRACKERS=${UPDATE_TRACKERS:-true}
      - CUSTOM_TRACKER_URL=${CUSTOM_TRACKER_URL}
      - TZ
    volumes:
      - ${ARIA_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${DOWNLOADS_DIR:?Downloads directory has to be set}:/downloads
    networks:
      - default
      - exposed
      - proxy
      - multimedia
    ports:
      - "${BT_LISTEN_PORT:-6881-6999}:${BT_LISTEN_PORT:-6881-6999}/tcp"
      - "${BT_LISTEN_PORT:-6881-6999}:${BT_LISTEN_PORT:-6881-6999}/udp"
    healthcheck:
      test: "netstat -ltun | grep -cqE -m 3 -e ':${RPC_PORT:-6800}' || exit 1"
    logging: # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.enable=true"
      # JSON-RPC/XML-RPC via TCP
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-rpc-tcp.rule=HostSNI(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose domain is not defined}`)"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-rpc-tcp.tls=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-rpc-tcp.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-rpc-tcp.service=${COMPOSE_PROJECT_NAME}-rpc-tcp"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-rpc-tcp.entrypoints=aria-rpc-tcp"
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-rpc-tcp.loadbalancer.server.port=${RPC_PORT:-6800}"
      # JSON-RPC/XML-RPC via UDP
      - "traefik.udp.routers.${COMPOSE_PROJECT_NAME}-rpc-udp.service=${COMPOSE_PROJECT_NAME}-rpc-udp"
      - "traefik.udp.routers.${COMPOSE_PROJECT_NAME}-rpc-udp.entrypoints=aria-rpc-udp"
      - "traefik.udp.services.${COMPOSE_PROJECT_NAME}-rpc-udp.loadbalancer.server.port=${RPC_PORT:-6800}"

  ariang:
    image: p3terx/ariang:${ARIANG_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    container_name: ${COMPOSE_PROJECT_NAME}-ng
    command: --port 6880 --ipv6
    networks:
      - default
    depends_on:
      aria2-pro:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=6880"

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  multimedia:
    external: true
