name: apprise

services:

  apprise:
    image: caronc/apprise:${APPRISE_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    networks:
      - proxy
      - smtp
      - exposed
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/attachments:/attach
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  smtp:
    external: true
  exposed:
    external: true
