name: ntfy

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: caronc/apprise:${APPRISE_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
      - smtp
      - exposed
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/config
      - /var/${COMPOSE_PROJECT_NAME}/attachments:/attach
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER?Certificate resolver is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  smtp:
    external: true
  exposed:
    external: true
