version: '3.9'
name: trillium
# Trilium Notes stack

# Page: https://github.com/zadam/trilium/wiki
# Dckr: https://github.com/zadam/trilium/wiki/Docker-server-installation
# Code: https://github.com/zadam/trilium

# Trilium Notes is a hierarchical note taking application
# with focus on building large personal knowledge bases

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: zadam/trilium:${TRILIUM_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ
      - TRILIUM_DATA_DIR=/home/node/data
      - TRILIUM_LOG_DIR=/home/node/log
      - TRILIUM_CONFIG_INI_PATH=/home/node/config/config.ini
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/home/node/data
      - /etc/${COMPOSE_PROJECT_NAME}/:/home/node/config
      - /var/log/${COMPOSE_PROJECT_NAME}:/home/node/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
