version: '3.9'
name: czkawka

services:

  czkawka:
    image: jlesage/czkawka:${CZKAWKA_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      - USER_ID=${CZKAWKA_UID:-1000}
      - GROUP_ID=${CZKAWKA_GID:-1000}
      - DARK_MODE=${CZKAWKA_RIGCZ_MODE:-0}
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - /etc/localtime:/etc/localtime:ro
      - /cabinet:/storage/cabinet
      - /drawer:/storage/drawer
      - /stockpile:/storage/stockpile
    networks:
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5800"

networks:
  proxy:
    external: true
  exposed:
    external: true
