version: '3.9'
name: czkawka

services:

  czkawka:
    image: jlesage/czkawka:${CZKAWKA_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      - USER_ID=${CZKAWKA_UID:-1000}
      - GROUP_ID=${CZKAWKA_GID:-1000}
      - DARK_MODE=${CZKAWKA_RIGCZ_MODE:-0}
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/config
      - /etc/localtime:/etc/localtime:ro
      - /cabinet:/storage/cabinet
      - /drawer:/storage/drawer
      - /stockpile:/storage/stockpile
    restart: unless-stopped
    networks:
      - proxy
      - exposed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5800"

networks:
  proxy:
    external: true
  exposed:
    external: true
