name: n8n

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/data:/home/node/.n8n
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/files:/files
    environment:
      N8N_HOST: ${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      DB_POSTGRESDB_HOST: ${COMPOSE_PROJECT_NAME}-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${DB_USER:-${COMPOSE_PROJECT_NAME}}
      DB_POSTGRESDB_PASSWORD: ${DB_PASS}
      NODE_ENV: production
      WEBHOOK_URL: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}/
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST: ${SMTP_HOST:-docker-mailserver}
      N8N_SMTP_PORT: ${SMTP_PORT:-25}
      N8N_SMTP_USER: ${SMTP_USER}
      N8N_SMTP_PASS: ${SMTP_PASS}
      N8N_SMTP_SENDER: "${COMPOSE_PROJECT_NAME} <${COMPOSE_PROJECT_NAME}@mail.${COMPOSE_DOMAIN}>"
      N8N_SMTP_SSL: ${SMTP_SSL:-true}
    networks:
      - default
      - exposed
      - proxy
      - smtp
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5678"

  postgres:
    extends:
      file: ../fragments/services.yml
      service: postgres

networks:
  deafault:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  smtp:
    external: true
