name: filebrowser

services:
  filebrowser:
    image: filebrowser/filebrowser:${FILEBROWSER_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-loc
    volumes:
      - ${ADDITIONAL_DIR:-/media}:/srv
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/database
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}/config.json:/.filebrowser.json
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
