version: '3.9'
name: netalertx

services:
  netalertx:
    image: jokobsk/netalertx:${NETALERTX_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/app/config
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/db}:/app/db
      - ${PROJECT_LOGS_DIR:-${LOGS_DIR:-/var/log}/${COMPOSE_PROJECT_NAME}}:/app/front/log
    environment:
      - TZ
    network_mode: host
