name: sabnzbd

services:

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:${SABNZBD_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TZ:-Etc/UTC}
    networks:
      - exposed
      - proxy
      - multimedia
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/config
      - /cabinet/download:/downloads
      - /cabinet/incomplete-download:/incomplete-downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${NETWORK_DOMAIN:?Netowrk domain is not defined}`, `${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN:?Machine domain is not defined}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  exposed:
    external: true
  multimedia:
    external: true
