name: sabnzbd

services:

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:${SABNZBD_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TZ:-Etc/UTC}
    networks:
      - exposed
      - multimedia
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${SABNZBD_DL_DIR:?No download directory set}:/downloads
      - ${SABNZBD_INCOMPLETE_DL_DIR:?No directory set for incomplete downloads}:/incomplete-downloads
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  exposed:
    external: true
  multimedia:
    external: true
