name: epicgames-freebies-claimer

services:

  epicgames-freebies-claimer:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ghcr.io/jackblk/epicgames-freebies-claimer:${EGSFC_TAG:-latest}
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/app/data
    networks:
      - exposed

networks:
  exposed:
    external: true
