name: vaultwarden

services:

  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_TAG:-alpine}
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - proxy
      - exposed
      - smtp
    environment:
      - WEBSOCKET_ENABLED
    volumes:
      - data:/data/
    labels:
      - "traefik.enable=true"
      # HTTP(S) service
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=${VAULTWARDEN_CUSTOM_SUBDOMAIN:+Host(`${VAULTWARDEN_CUSTOM_SUBDOMAIN}.${COMPOSE_DOMAIN}`) || }Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  exposed:
    external: true
  smtp:
    external: true

volumes:
  data:
