name: flyimg

services:

  flyimg:
    container_name: flyimg
    image: flyimg/flyimg-build:${FLYIMG_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}/parameters.yml:/var/www/html/config/parameters.yml
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SUBDOMAIN:-$COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  exposed:
    external: true
  proxy:
    external: true
