name: gitea-act-runner

services:

  gitea-act-runner:
    image: gitea/act_runner:${GITEA_ACT_RUNNER_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main
    environment:
      CONFIG_FILE: /config/config.yaml
      GITEA_INSTANCE_URL: "${INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "${RUNNER_NAME}"
      GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - exposed

networks:
  exposed:
    external: true
