name: netbootxyz

services:

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:${NETBOOTXYZ_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/assets
    networks:
      - exposed
    ports:
      - 69:69/udp # nice
    cap_add: # More info: https://github.com/samdbmg/dhcp-netboot.xyz
      - NET_ADMIN
    healthcheck:
      #test: "(ps -o comm | grep -q -m 1 tftpd) && (ps -o comm | grep -q -m 1 nginx) && (curl --fail --silent http://localhost/ > /dev/null) || exit 1"
      test: "(ps -o comm | grep -q -m 1 nginx) && (curl --fail --silent http://localhost/ > /dev/null) || exit 1"
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-assets.rule=Host(`${COMPOSE_PROJECT_NAME}-assets.${COMPOSE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-assets.service=${COMPOSE_PROJECT_NAME}-assets"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-assets.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-assets.loadbalancer.server.port=80"

networks:
  exposed:
    external: true
  proxy:
    external: true
