name: actual

services:

  actual:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: actualbudget/actual-server:${ACTUAL_TAG:-latest}
    restart: unless-stopped
    healthcheck:
      test: 'cat /proc/net/tcp6 /proc/net/tcp | grep -iEsqe "^[ \0A-F]+: 0+:`printf \"%x\" 5006` [\0A-F:]+ 0A "'
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 2s
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/data
    networks:
      - proxy
      - exposed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5006"

networks:
  proxy:
    external: true
  exposed:
    external: true
