name: actual

services:

  actual:
    image: actualbudget/actual-server:${ACTUAL_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    healthcheck:
      test: 'cat /proc/net/tcp6 /proc/net/tcp | grep -iEsqe "^[ \0A-F]+: 0+:`printf \"%x\" 5006` [\0A-F:]+ 0A "'
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
    environment:
      ACTUAL_LOGIN_METHOD: header
      ACTUAL_TRUSTED_PROXIES: "[10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7, ::1/128]"
    networks:
      - exposed
    labels:
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers.headers.customrequestheaders.X-Forwarded-For="
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined},${COMPOSE_PROJECT_NAME}-headers"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5006"

networks:
  proxy:
    external: true
  exposed:
    external: true
