name: ${STACK_NAME:-gitea}

include:
  - ../fragments/network-default.yml
  - ../fragments/network-outgoing.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-smtp.yml
  - ../fragments/service-postgres.yml

services:

  gitea:
    image: gitea/gitea:${GITEA_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${GITEA_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/data}:/data
    ports:
      - "${GITEA_SSH_PORT:-222}:22"
    environment:
      USER_UID: ${GITEA_UID:-1000}
      USER_GID: ${GITEA_GID:-1000}
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: ${COMPOSE_PROJECT_NAME}-db
      GITEA__database__NAME: ${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      GITEA__database__USER: ${DB_USER:-${COMPOSE_PROJECT_NAME}}
      GITEA__database__PASSWD: ${DB_PASS}
      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: ${MAIL_FROM:-"Gitea <no-reply@${COMPOSE_DOMAIN}>"}
      GITEA__mailer__PROTOCOL: ${MAIL_PROT:-smtp}
      GITEA__mailer__SMTP_ADDR: ${MAIL_ADDR:-docker-mailserver}
      GITEA__mailer__SMTP_PORT: ${MAIL_PORT:-25}
      GITEA__mailer__USER: ${MAIL_USER:-}
      GITEA__mailer__PASSWD: ${MAIL_PASS:-}
      GITEA__security__SECRET_KEY: ${GITEA_KEY:?Gitea secret key is missing}
      GITEA__security__INTERNAL_TOKEN: ${GITEA_TOKEN:?Gitea internal token is missing}
    networks:
      - default
      - outgoing
      - proxy
      - smtp
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
