name: gitea

services:

  n8n:
    image: gitea/gitea:${GITEA_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/data:/data
    ports:
      - "${GITEA_SSH_PORT:-222}:22"
    environment:
      USER_UID: ${GITEA_UID:-1000}
      USER_GID: ${GITEA_GID:-1000}
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: ${COMPOSE_PROJECT_NAME}-db
      GITEA__database__NAME: ${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      GITEA__database__USER: ${DB_USER:-${COMPOSE_PROJECT_NAME}}
      GITEA__database__PASSWD: ${DB_PASS}
      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: "Gitea <${COMPOSE_PROJECT_NAME}@mail.${COMPOSE_DOMAIN}>"
      GITEA__mailer__PROTOCOL: smtp
      GITEA__mailer__SMTP_ADDR: docker-mailserver
      GITEA__mailer__SMTP_PORT: 25
      GITEA__mailer__USER: ${GITEA_SMTP_USER}
      GITEA__mailer__PASSWD: ${GITEA_SMTP_PASS}
      GITEA__security__SECRET_KEY: ${GITEA_KEY}
      GITEA__security__INTERNAL_TOKEN: ${GITEA_TOKEN}
    networks:
      - default
      - exposed
      - proxy
      - smtp
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

  postgres:
    extends:
      file: ../fragments/services.yml
      service: postgres

networks:
  deafault:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  smtp:
    external: true
