name: cyberchef

services:

  cyberchef:
    image: ghcr.io/gchq/cyberchef:${CYBERCHEF_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  exposed:
    external: true
  proxy:
    external: true
