name: filestash

services:

  filestash:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: machines/filestash:${FILESTASH_TAG:-latest}
    user: "${FILESTASH_UID:-1000}:${FILESTASH_GID:-1000}"
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/app/data/state
    restart: unless-stopped
    env_file: stack.env
    networks:
      - default
      - exposed
      - proxy
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Netowrk domain is not defined}`) || Host(`${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN:?Machine domain is not defined}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8334"

  filestash-onlyoffice:
    container_name: ${COMPOSE_PROJECT_NAME}-onlyoffice
    image: onlyoffice/documentserver
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    networks:
      - default

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  smtp:
    external: true
