name: free-games-claimer

services:

  free-games-claimer:
    image: ghcr.io/vogler/free-games-claimer:${FGC_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    command: >-
      bash -c "node prime-gaming; node gog; echo sleeping; sleep 1d"
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/fgc/data
    env_file: stack.env
    networks:
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=6080"

networks:
  proxy:
    external: true
  exposed:
    external: true
