name: nextcloud

services:

  nextcloud:
    image: nextcloud:${NEXTCLOUD_TAG:-stable}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    volumes: &nextcloud-volumes
      - ${NEXTCLOUD_MAIN:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/app}:/var/www/html
      - ${NEXTCLOUD_CUSTOM_APPS:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/apps}:/var/www/html/custom_apps
      - ${NEXTCLOUD_CONFIG:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/var/www/html/config
      - ${NEXTCLOUD_DATA:-/var/${COMPOSE_PROJECT_NAME}/data}:/data:z
      - ${NEXTCLOUD_CUSTOM_THEME:-/var/${COMPOSE_PROJECT_NAME}/theme}:/var/www/html/themes/${MACHINE_DOMAIN}
    environment: &nextcloud-environment
      NEXTCLOUD_DATA_DIR: /data
      PHP_UPLOAD_LIMIT: ${NEXTCLOUD_UPLOAD_LIMIT:-512M}
      PHP_MEMORY_LIMIT: ${NEXTCLOUD_MEMORY_LIMIT:-512M}
      APACHE_BODY_LIMIT: ${NEXTCLOUD_BODY_LIMIT:-1073741824}
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER:-${COMPOSE_PROJECT_NAME}}
      POSTGRES_HOST: ${COMPOSE_PROJECT_NAME}-db
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADM_USER:?Admin username has to be set}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADM_PASS:?Admin password has to be set}
      REDIS_HOST: ${COMPOSE_PROJECT_NAME}-kv
      TRUSTED_PROXIES: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      NEXTCLOUD_TRUSTED_DOMAINS: "${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}"
      NEXTCLOUD_DOMAIN_NAME: ${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}
    restart: unless-stopped
    depends_on: &nextcloud-dependencies
      nextcloud-db:
        condition: service_healthy
      nextcloud-kv:
        condition: service_healthy
    networks: &nextcloud-networks
      - default
      - exposed
      - proxy
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

  nextcloud-db:
    extends:
      file: ../fragments/services.yml
      service: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  nextcloud-kv:
    extends:
      file: ../fragments/services.yml
      service: valkey-persistent

  nextcloud-cron:
    image: nextcloud:${NEXTCLOUD_CRON_TAG:-apache}
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    extends:
      file: ../fragments/services.yml
      service: service-sub
    volumes: *nextcloud-volumes
    environment: *nextcloud-environment
    entrypoint: /cron.sh
    networks: *nextcloud-networks
    depends_on: *nextcloud-dependencies

networks:
  default:
  exposed:
    external: true
  proxy:
    external: true
