name: homeassistant

services:

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:${HOMEASSISTANT_TAG:-stable}
    extends:
      file: ../fragments/services.yml
      service: service-main-hc
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/${ZIGBEE_DEV_ID:?Zigbee device ID missing}:/dev/ttyACM0
    privileged: true
    network_mode: host
    healthcheck:
      test: "curl -f http://localhost:8123/ || exit 1"
