name: romm

services:

  romm-db:
    extends:
      file: ../fragments/services.yml
      service: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:?Database root password is missing}

  romm:
    image: rommapp/romm:${ROMM_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      - DB_HOST=${COMPOSE_PROJECT_NAME}-db
      - DB_NAME=${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      - DB_USER=${DB_USER:-${COMPOSE_PROJECT_NAME}}
      - DB_PASSWD=${DB_PASS}
      - IGDB_CLIENT_ID=${IGDB_ID:?IGDB client ID missing}
      - IGDB_CLIENT_SECRET=${IGDB_SECRET:?IGDB client secret missing}
      - ROMM_AUTH_SECRET_KEY=${ROMM_SECRET:?RomM secret key missing}
      - ROMM_AUTH_USERNAME=${ROMM_USER:-admin}
      - ROMM_AUTH_PASSWORD=${ROMM_PASS:-admin}
    depends_on:
      romm-db:
        condition: service_healthy
    volumes:
      - ${PROJECT_RESOURCES_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/resources}:/romm/resources
      - ${PROJECT_REDIS_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/redis}:/redis-data
      - ${PROJECT_LIBRARY_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/library}:/romm/library
      - ${PROJECT_ASSETS_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/assets}:/romm/assets
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/romm/config
      - ${PROJECT_LOGS_DIR:-${LOGS_DIR:-/var/log}/${COMPOSE_PROJECT_NAME}}:/romm/logs
    networks:
      - default
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
