name: diun

services:

  app:
    hostname: ${COMPOSE_PROJECT_NAME}
    image: crazymax/diun:${DIUN_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-hc
    env_file: stack.env
    networks:
      - exposed
      - mqtt
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/etc/diun
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "(ps -o comm | grep -q -m 1 diun) || exit 1"

networks:
  exposed:
    external: true
  mqtt:
    external: true
