name: backrest

services:
  app:
    container_name: backrest
    image: garethgeorge/backrest:${BACKREST_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}:/data
      - /etc/${COMPOSE_PROJECT_NAME}:/config
      - /tmp/${COMPOSE_PROJECT_NAME}:/cache
      - /backup:/repos
      - /etc:/userdata/etc:ro
      - /home:/userdata/home:ro
      - /opt:/userdata/opt:ro
      - /srv:/userdata/srv:ro
      - /var:/userdata/var:ro
    environment:
      - BACKREST_DATA
      - BACKREST_CONFIG
      - XDG_CACHE_HOME
    hostname: backrest
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9898"

networks:
  exposed:
    external: true
  proxy:
    external: true
