name: music-assistant

services:

  music-assistant:
    image: ghcr.io/music-assistant/server:${MASS_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
      - ${MUSIC_DIR:?Directory for music library has to be set}:/music
    network_mode: host
    privileged: true
