name: watchtower

services:

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-loc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH:-/root/.docker/config.json}:/config.json
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NO_RESTART: true
      WATCHTOWER_HTTP_API_METRICS: true
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_TOKEN:?Watchtower API token has to be set}
      WATCHTOWER_SCHEDULE: "0 0 */6 * * *"
    networks:
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  exposed:
    external: true
