name: immich

services:

  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_TAG:-release}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    group_add:
      - "${RENDER_GROUP:?Host render group ID missing}"
    devices:
      - ${GPU_DEV:-/dev/dri/renderD128}:${GPU_DEV:-/dev/dri/renderD128} # For hwaccel
    volumes:
      - ${UPLOAD_LOCATION:?Upload directory has to be set}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      immich-kv:
        condition: service_healthy
      immich-db:
        condition: service_healthy
    networks:
      - default
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3001"

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_ML_TAG:-release}
    container_name: ${COMPOSE_PROJECT_NAME}-ml
    extends:
      file: ../fragments/services.yml
      service: service-sub-hc
    volumes:
      - ${PROJECT_ML_CACHE_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/ml}:/cache
    env_file:
      - stack.env

  immich-kv:
    container_name: ${COMPOSE_PROJECT_NAME}-kv
    extends:
      file: ../fragments/services.yml
      service: valkey-ephemeral

  immich-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: tensorchord/pgvecto-rs:${IMMICH_DB_TAG:-pg14-v0.2.0}
    extends:
      file: ../fragments/services.yml
      service: postgres

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
