name: directus

services:

  directus:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: directus/directus:${DIRECTUS_TAG:-latest}
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/uploads:/directus/uploads
      - /srv/${COMPOSE_PROJECT_NAME}/extensions:/directus/extensions
    restart: unless-stopped
    depends_on:
      - directus-db
    environment:
      KEY: ${DIRECTUS_KEY:?Directus key is missing}
      SECRET: ${DIRECTUS_SECRET:?Directus secret is missing}
      DB_CLIENT: pg
      DB_HOST: ${COMPOSE_PROJECT_NAME}-db
      DB_PORT: 5432
      DB_DATABASE: ${DIRECTUS_DB_NAME:-directus}
      DB_USER: ${DIRECTUS_DB_USER:-directus}
      DB_PASSWORD: ${DIRECTUS_DB_PASS:?Directus database password missing}
      ADMIN_EMAIL: ${DIRECTUS_MAIL:?Directus admin email missing}
      ADMIN_PASSWORD: ${DIRECTUS_PASS:?Directus admin password missing}
      WEBSOCKETS_ENABLED: "true"
      STORAGE_LOCAL_ROOT: /directus/uploads
    networks:
      - default
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}`, `${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8055"

  directus-db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgis/postgis:13-master
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DIRECTUS_DB_USER:-directus}
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASS}
      POSTGRES_DB: ${DIRECTUS_DB_NAME:-directus}
    networks:
      - default

networks:
  default:
  exposed:
    external: true
  proxy:
    external: true
