name: mqttx

services:

  mqttx:
    image: emqx/mqttx-web:latest
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    networks:
      - exposed
      - mqtt
    healthcheck:
      test: "(ps -o comm | grep -q -m 1 http-server) && wget -q --spider http://127.0.0.1:80/ || exit 1"
    labels:
      - "traefik.http.services.mqttx.loadbalancer.server.port=80"

networks:
  exposed:
    external: true
  proxy:
    external: true
  mqtt:
    external: true
