name: sshwifty

services:

  sshwifty:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: niruix/sshwifty:${SSHWIFTY_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /etc/${COMPOSE_PROJECT_NAME}:/config
    environment:
      SSHWIFTY_CONFIG: /config/sshwifty.conf.json
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SUBDOMAIN:-$COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8182"

networks:
  exposed:
    external: true
  proxy:
    external: true
