name: vscode

services:

  vscode:
    image: codercom/code-server:${VSCODE_TAG:-debian}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-loc-hc
    user: root
    entrypoint: /usr/bin/entrypoint.sh --bind-addr 0.0.0.0:8080 --disable-telemetry --disable-update-check --extensions-dir /extensions --user-data-dir /user --auth none /workspace
    healthcheck:
      test: "(ps -o comm | grep -q -m 1 node) && curl --fail http://127.0.0.1:8080/healthz || exit 1"
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/home/coder/.config/code-server/
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/extensions:/extensions
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/userdata:/user
      - ${CONF_DIR:-/etc}:/workspace/config
      - ${DATA_DIR:-/srv}:/workspace/data
      - ${LOGS_DIR:-/var/log}:/workspace/log
    networks:
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  exposed:
    external: true
  proxy:
    external: true
