name: reactive-resume

include:
  - ../fragments/network-default.yml
  - ../fragments/network-outgoing.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-s3.yml
  - ../fragments/network-smtp.yml
  - ../fragments/service-postgres.yml
  - ../fragments/service-valkey-persistent.yml

services:

  chrome:
    container_name: ${COMPOSE_PROJECT_NAME}-chrome
    image: ghcr.io/browserless/chromium:${RR_CHROME_VERSION:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-sub-hc
    environment:
      HEALTH: "true"
      TIMEOUT: ${RR_CHROME_TIMEOUT:-10000}
      CONCURRENT: ${RR_CHROME_CONCURRENT:-10}
      TOKEN: ${RR_CHROME_TOKEN:-chrome_token}
      PROXY_HOST: "${PRINTER_DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}-printer.${COMPOSE_DOMAIN}}"
      PROXY_PORT: 443
      PROXY_SSL: "true"
    networks:
      - default
      - outgoing
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-chrome.rule=${PRINTER_DOMAIN_OVERRIDE:+Host(`${PRINTER_DOMAIN_OVERRIDE:-}`) || }Host(`${COMPOSE_PROJECT_NAME}-printer.${COMPOSE_DOMAIN:?Compose FQDN missing}`)${OPTIONAL_PRINTER_ROUTER_RULES:+ || ${OPTIONAL_PRINTER_ROUTER_RULES:-}}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-chrome.service=${COMPOSE_PROJECT_NAME}-chrome"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-chrome.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-chrome.loadbalancer.server.port=3000"

  reactive-resume:
    image: amruthpillai/reactive-resume:${REACTIVE_RESUME_VERSION:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      chrome:
        condition: service_started
    networks:
      - default
      - outgoing
      - proxy
      - smtp
      - s3
    environment:
      PORT: 3000
      NODE_ENV: production
      PUBLIC_URL: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}
      STORAGE_URL: ${RR_STORAGE_URL:-}
      CHROME_TOKEN: ${RR_CHROME_TOKEN:-chrome_token}
      CHROME_URL: wss://${PRINTER_DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}-printer.${COMPOSE_DOMAIN}}
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASS:-postgres}@${COMPOSE_PROJECT_NAME}-db:5432/${DB_NAME:-postgres}
      ACCESS_TOKEN_SECRET: ${RR_ACCESS_TOKEN_SECRET:-access_token_secret}
      REFRESH_TOKEN_SECRET: ${RR_REFRESH_TOKEN_SECRET:-refresh_token_secret}
      MAIL_FROM: ${RR_MAIL_FROM:-Mail from address has to be set}
      SMTP_URL: ${RR_MAIL_SMTP:-SMTP URL has to be set}
      STORAGE_ENDPOINT: ${RR_STORAGE_ENDPOINT:-}
      STORAGE_PORT: ${RR_STORAGE_PORT:-443}
      STORAGE_REGION: ${RR_STORAGE_REGION:-}
      STORAGE_BUCKET: ${RR_STORAGE_BUCKET:-${COMPOSE_PROJECT_NAME}}
      STORAGE_ACCESS_KEY: ${RR_STORAGE_ACCESS_KEY:-}
      STORAGE_SECRET_KEY: ${RR_STORAGE_SECRET_KEY:-}
      STORAGE_USE_SSL: ${RR_STORAGE_USE_SSL:-true}
      STORAGE_SKIP_BUCKET_CHECK: ${RR_STORAGE_SKIP_BUCKET_CHECK:-true}
      REDIS_URL: redis://${COMPOSE_PROJECT_NAME}-kv:6379
      DISABLE_EMAIL_AUTH: ${RR_DISABLE_EMAIL:-true}
      VITE_DISABLE_SIGNUPS: ${RR_DISABLE_SIGNUPS:-true}
      GITHUB_CLIENT_ID: ${RR_GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${RR_GITHUB_CLIENT_SECRET:-}
      GITHUB_CALLBACK_URL: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}/api/auth/github/callback
      GOOGLE_CLIENT_ID: ${RR_GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${RR_GOOGLE_CLIENT_SECRET:-}
      GOOGLE_CALLBACK_URL: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}/api/auth/google/callback
      VITE_OPENID_NAME: ${RR_OPENID_NAME:-OpenID}
      OPENID_AUTHORIZATION_URL: ${RR_OPENID_AUTH:-}
      OPENID_CALLBACK_URL: ${RR_OPENID_CALLBACK:-https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}/api/auth/openid/callback}
      OPENID_CLIENT_ID: ${RR_OPENID_ID:-}
      OPENID_CLIENT_SECRET: ${RR_OPENID_SECRET:-}
      OPENID_ISSUER: ${RR_OPENID_ISSUER:-}
      OPENID_SCOPE: ${RR_OPENID_SCOPE:-openid profile email}
      OPENID_TOKEN_URL: ${RR_OPENID_TOKEN:-}
      OPENID_USER_INFO_URL: ${RR_OPENID_INFO:-}
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=cors-allow-all@file"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
