name: web-check

services:

  web-check:
    image: lissy93/web-check:${WEBCHECK_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    env_file: stack.env
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware name missing}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

networks:
  exposed:
    external: true
  proxy:
    external: true
