name: upsnap

services:

  upsnap:
    image: ghcr.io/seriousm4x/upsnap:${UPSNAP_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-hc
    network_mode: host
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/app/pb_data
    environment:
      - UPSNAP_SCAN_RANGE
    healthcheck:
      test: curl -fs "http://127.0.0.1:8090/api/health" || exit 1
