name: whatsupdocker

services:

  whatsupdocker:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: fmartinou/whats-up-docker:${WUD_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/${COMPOSE_PROJECT_NAME}/store:/store
      - /srv/portainer/compose:/compose
    environment:
      - WUD_AUTH_OIDC_AUTHENTIK_CLIENTID=${WUD_OIDC_CLIENT:?Missing client ID for OIDC auth provider}
      - WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET=${WUD_OIDC_SECRET:?Missing client secret for OIDC auth provicder}
      - WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY=${WUD_OIDC_URL}/application/o/${WUD_OIDC_NAME:-$COMPOSE_PROJECT_NAME}/.well-known/openid-configuration
      - WUD_AUTH_OIDC_AUTHENTIK_REDIRECT=${WUD_OIDC_DIRECT:-true}
      - WUD_LOG_LEVEL=debug
    healthcheck:
      test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:3000
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${MACHINE_DOMAIN:?Machine FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER:?Cert resolver name missing}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

networks:
  exposed:
    external: true
  proxy:
    external: true
