name: outline

services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:${OUTLINE_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/data:/var/lib/outline/data
    env_file: stack.env
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - default
      - exposed
      - proxy
      - smtp
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"

  postgres:
    extends:
      file: ../fragments/services.yml
      service: postgres

  valkey:
    extends:
      file: ../fragments/services.yml
      service: valkey-ephemeral

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  smtp:
    external: true
