name: beszel-agent

services:

  beszel-agent:
    image: henrygd/beszel-agent:${BESZEL_AGENT_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      KEY: ${PUBLIC_KEY:?Public SSH key has to be defined.}
    network_mode: host
