name: jellyfin

services:

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    hostname: ${COMPOSE_PROJECT_NAME}
    group_add:
      - "${RENDER_GROUP:?Host render group ID missing}"
    devices:
      - ${GPU_DEV:-/dev/dri/renderD128}:${GPU_DEV:-/dev/dri/renderD128} # For hwaccel
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - ${JELLYFIN_CACHE_DIR:?Cache directory not set}:/cache
      - ${JELLYFIN_MEDIA_DIR:?Media directory not set}:/media
    networks:
      - exposed
      - multimedia
    ports:
      - 8096:8096
    healthcheck:
      test: "curl -f http://localhost:8096/ || exit 1"
    environment:
      JELLYFIN_PublishedServerUrl: https://${COMPOSE_PROJECT_NAME}.${NETWORK_DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8096"

networks:
  exposed:
    external: true
  proxy:
    external: true
  multimedia:
    external: true
