name: dozzle

services:

  dozzle:
    image: amir20/dozzle:${DOZZLE_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-loc-hc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
    networks:
      - exposed
    environment:
      DOZZLE_ENABLE_ACTIONS: ${DOZZLE_ACTIONS_ENABLE:-true}
      DOZZLE_HOSTNAME: ${MACHINE_DOMAIN}
      DOZZLE_NO_ANALYTICS: ${DOZZLE_ANALYTICS_DISABLE:-false}
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  exposed:
    external: true
  proxy:
    external: true
