name: node-red

services:
  app:
    image: nodered/node-red:${NODERED_TAG:-latest}
    hostname: ${COMPOSE_PROJECT_NAME}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      - TZ
    networks:
      - exposed
      - smarthome
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/data
    labels:
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"

networks:
  exposed:
    external: true
  proxy:
    external: true
  smarthome:
    external: true
