name: ${STACK_NAME:-ghost}

services:

  ghost:
    image: ghost:${GHOST_VERSION:-alpine}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      url: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}
      database__client: ${GHOST_DB_ENGINE:-mysql}
      database__connection__host: ${DB_HOST:-${COMPOSE_PROJECT_NAME}-db}
      database__connection__user: ${DB_USER:-root}
      database__connection__password: ${DB_PASS:?Database password has to be set}
      database__connection__database: ${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      mail__from: ${GHOST_MAIL_FROM:-support@example.com}
      mail__transport: ${GHOST_MAIL_TRANSPORT:-SMTP}
      mail__options__service: ${GHOST_MAIL_SERVICE}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT:-465}
      mail__options__secure: ${GHOST_MAIL_USETLS:-true}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASS}
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/content:/var/lib/ghost/content
    networks:
      default:
        priority: 40
      exposed:
        priority: 10
      proxy:
        priority: 20
      smtp:
        priority: 30
    depends_on:
      mysql:
        condition: service_started
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2368"

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mysql:${GHOST_DB_VERSION:-8.0}
    extends:
      file: ../fragments/services.yml
      service: service-sub
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}/db:/var/lib/mysql
    networks:
      - default

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true
  smtp:
    external: true
