name: ${STACK_NAME:-ghost}

include:
  - ../fragments/network-default.yml
  - ../fragments/network-outgoing.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-smtp.yml
  - ../fragments/service-mysql.yml

services:

  ghost:
    image: ghost:${GHOST_TAG:-alpine}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      NODE_ENV: production
      url: https://${DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}}
      database__client: ${GHOST_DB_ENGINE:-mysql}
      database__connection__host: ${DB_HOST:-${COMPOSE_PROJECT_NAME}-db}
      database__connection__user: ${DB_USER:-root}
      database__connection__password: ${DB_PASS:?Database password has to be set}
      database__connection__database: ${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      mail__from: ${MAIL_FROM:-support@example.com}
      mail__transport: ${MAIL_PROT:-SMTP}
      mail__options__service: ${MAIL_SERV:-}
      mail__options__host: ${MAIL_HOST:-}
      mail__options__port: ${MAIL_PORT:-465}
      mail__options__secure: ${MAIL_USETLS:-true}
      mail__options__auth__user: ${MAIL_USER:-}
      mail__options__auth__pass: ${MAIL_PASS:-}
    volumes:
      - ${CONTENT_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/content}:/var/lib/ghost/content
    networks:
      default:
        priority: 40
      smtp:
        priority: 30
      proxy:
        priority: 20
      outgoing:
        priority: 10
    dns: &dns-servers
      - 1.1.1.1 # Cloudflare
      - 208.67.222.222 # OpenDNS
      - 94.140.14.14 # AdGuard
    depends_on:
      mysql:
        condition: service_started
      activitypub:
        condition: service_started
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2368"

  mysql:
    environment:
      MYSQL_MULTIPLE_DATABASES: activitypub

  activitypub:
    container_name: ${COMPOSE_PROJECT_NAME}-activitypub
    image: ghcr.io/tryghost/activitypub:${GHOST_ACTIVITYPUB_TAG:-1}
    extends:
      file: ../fragments/services.yml
      service: service-sub
    volumes:
      - ${CONTENT_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/content}:/opt/activitypub/content
    environment:
      # See https://github.com/TryGhost/ActivityPub/blob/main/docs/env-vars.md
      NODE_ENV: production
      MYSQL_HOST: ${DB_HOST:-${COMPOSE_PROJECT_NAME}-db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-}
      MYSQL_DATABASE: activitypub
      LOCAL_STORAGE_PATH: /opt/activitypub/content/images/activitypub
      LOCAL_STORAGE_HOSTING_URL: https://${ACTIVITYPUB_DOMAIN_OVERRIDE:-${COMPOSE_PROJECT_NAME}-activitypub.${COMPOSE_DOMAIN:-}}/content/images/activitypub
    depends_on:
      mysql:
        condition: service_started
      activitypub-migrate:
        condition: service_completed_successfully
    networks:
      default:
        priority: 40
      proxy:
        priority: 20
      outgoing:
        priority: 10
    dns: *dns-servers
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-activitypub.service=${COMPOSE_PROJECT_NAME}-activitypub"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-activitypub.entrypoints=http,https"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-activitypub.rule=${ACTIVITYPUB_DOMAIN_OVERRIDE:+Host(`${ACTIVITYPUB_DOMAIN_OVERRIDE:-}`) || }Host(`${COMPOSE_PROJECT_NAME}-activitypub.${COMPOSE_DOMAIN:?Compose FQDN missing}`)${OPTIONAL_ACTIVITYPUB_ROUTER_RULES:+ || ${OPTIONAL_ACTIVITYPUB_ROUTER_RULES:-}}"

  activitypub-migrate:
    container_name: ${COMPOSE_PROJECT_NAME}-activitypub-migrate
    image: ghcr.io/tryghost/activitypub-migrations:${GHOST_ACTIVITYPUB_MIGRATIONS_TAG:-1}
    environment:
      MYSQL_DB: mysql://${DB_USER:-root}:${DB_PASS:-}@tcp(${DB_HOST:-${COMPOSE_PROJECT_NAME}-db}:3306)/activitypub
    networks:
      default:
        priority: 40
    depends_on:
      mysql:
        condition: service_started
    restart: no
