name: beszel

services:

  beszel:
    image: henrygd/beszel:${BESZEL_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/beszel_data
    networks:
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8090"

networks:
  proxy:
    external: true
  exposed:
    external: true
