name: ${STACK_NAME:-anonaddy}

include:
  - ../fragments/network-default.yml
  - ../fragments/network-proxy.yml
  - ../fragments/network-outgoing.yml
  - ../fragments/service-mariadb.yml
  - ../fragments/service-valkey-persistent.yml

services:

  anonaddy:
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    image: anonaddy/anonaddy:${ANONADDY_TAG:-latest}
    depends_on:
      mariadb:
        condition: service_healthy
      valkey:
        condition: service_healthy
    volumes:
      - ${ANONADDY_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/app}:/data
      - ${LETSENCRYPT_DIR:-/etc/letsencrypt}:/etc/letsencrypt:ro
    env_file: stack.env
    environment:
      - DB_HOST=${COMPOSE_PROJECT_NAME}-db
      - DB_DATABASE=${DB_NAME:-${COMPOSE_PROJECT_NAME}}
      - DB_USERNAME=${DB_USER:-${COMPOSE_PROJECT_NAME}}
      - DB_PASSWORD=${DB_PASS:-}
      - REDIS_HOST=${COMPOSE_PROJECT_NAME}-kv
    ports:
      - 25:25/tcp
    networks:
      - default
      - proxy
      - outgoing
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8000"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rspamd.rule=Host(`${COMPOSE_PROJECT_NAME}-rspamd.${COMPOSE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rspamd.service=${COMPOSE_PROJECT_NAME}-rspamd"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rspamd.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-rspamd.loadbalancer.server.port=11334"

  # Used to host /.well-known static files
  # Enables setting up MTA-STS
  well-known:
    image: nginx:${ANONADDY_NGINX_TAG:-alpine}
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    extends:
      file: ../fragments/services.yml
      service: service-sub
    volumes:
      - ${WELL_KNOWN_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}/well-known}:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=(Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}`) || ${MTA_STS_HOSTS:-Host(`mta-sts.${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN}`)}) && PathPrefix(`/.well-known`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.service=${COMPOSE_PROJECT_NAME}-nginx"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"
