name: stirling-pdf

services:

  stirling-pdf:
    image: frooodle/s-pdf:${STIRLINGPDF_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      - DOCKER_ENABLE_SECURITY
    networks:
      - exposed
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/configs/
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/customFiles/
      - ${TESSERACT_DATA:-/usr/share/tesseract-ocr/5/tessdata}:/usr/share/tesseract-ocr/5/tessdata/
      - ${PROJECT_LOGS_DIR:-${LOGS_DIR:-/var/log}/${COMPOSE_PROJECT_NAME}}:/logs/
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  exposed:
    external: true
