name: uptime-kuma

services:

  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIMEKUMA_TAG:-alpine}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-loc-hc
    networks:
      - exposed
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3001"

networks:
  exposed:
    external: true
  proxy:
    external: true
