name: hrconvert2

services:

  hrconvert2:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: zelon88/hrconvert2:${HRCONVERT2_TAG:-v3.3.3}
    restart: unless-stopped
    volumes:
      - /var/log/${COMPOSE_PROJECT_NAME}:/var/www/html/HRProprietary/HRConvert2/Logs
    networks:
      - exposed
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SUBDOMAIN:-$COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose FQDN missing}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${AUTH_MIDDLEWARE:?Auth middleware is not defined}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

networks:
  exposed:
    external: true
  proxy:
    external: true
