name: esphome

services:

  app:
    image: ghcr.io/esphome/esphome:${ESPHOME_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-hc
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      test: "(curl --fail --silent http://localhost:6052/ > /dev/null) || exit 1"
    privileged: true
    network_mode: host
    environment:
      ESPHOME_DASHBOARD_USE_PING: ${ESPHOME_USE_PING:-true}
