name: dashy

services:

  dashy:
    image: lissy93/dashy:${DASHY_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    volumes:
      - ${PROJECT_CONF_DIR:-${CONF_DIR:-/etc}/${COMPOSE_PROJECT_NAME}}:/app/user-data
    environment:
      - NODE_ENV=${DASHY_ENV:-production}
      - UID=${DASHY_UID:-1000}
      - GID=${DASHY_GID:-1000}
    networks:
      - exposed
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  exposed:
    external: true
  proxy:
    external: true
