name: zigbee2mqtt

services:

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:${Z2M_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb-hc
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/${ZIGBEE_DEV_ID:?Zigbee device ID missing}:/dev/ttyACM0
    networks:
      - exposed
    environment:
      - TZ
    healthcheck:
      test: "(ps -o comm | grep -q -m 1 node) && wget -q --spider http://127.0.0.1:8080/|| exit 1"
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  exposed:
    external: true
