name: tandoor

services:

  tandoor:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: vabene1111/recipes:${TANDOOR_TAG:-latest}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - nginx_config:/opt/recipes/nginx/conf.d
      - staticfiles:/opt/recipes/staticfiles
      - /srv/${COMPOSE_PROJECT_NAME}/media:/opt/recipes/mediafiles
    env_file: stack.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      default:
        aliases:
          - web_recipes
      exposed:

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-http
    image: nginx:${TANDOOR_NGINX_TAG:-mainline-alpine}
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - /srv/${COMPOSE_PROJECT_NAME}/media:/media:ro
    depends_on:
      - tandoor
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${COMPOSE_DOMAIN:?Compose domain is not defined}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http,https"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:${TANDOOR_DB_TAG:-16-alpine}
    env_file: stack.env
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - /srv/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql/data

networks:
  default:
    internal: true
  exposed:
    external: true
  proxy:
    external: true

volumes:
  nginx_config:
  staticfiles:
