# Workflow to process all manifest files and templates to generate and update Markdown files

name: Update Markdown files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-markdown-pr:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    name: Update Markdown files
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run yml2md.go
        run: go run .
      - name: Set up Go environment
        uses: actions/setup-go@v4
      - name: Build and run yml2md
        run: |
          go build -v ./yml2md.go
          ./yml2md
      - name: Create pull request with updates
        id: yml2md-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit_message: Updated Markdown files
          title: 'chore(docs): Markdown files updated'
          body: |
            - Updated Markdown files according to `manifest.yml` files.

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
          add-paths: '**/*.md'
          branch: yml2md/update-markdown
          branch-suffix: short-commit-hash
          labels: automated,docs
          assignees: sowiszcze
          reviewers: sowiszcze
      - name: Check outputs
        if: ${{ steps.yml2md-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.yml2md-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.yml2md-pr.outputs.pull-request-url }}"
