name: manyfold

services:

  manyfold:
    image: ghcr.io/manyfold3d/manyfold:${MANYFOLD_TAG:-latest}
    extends:
      file: ../fragments/services.yml
      service: service-main-web-glb
    environment:
      SECRET_KEY_BASE: ${MANYFOLD_SECRET_BASE:?Secret key base has to be set}
      REDIS_URL: redis://${COMPOSE_PROJECT_NAME}-kv:6379/1
      DATABASE_URL: postgresql://${MANYFOLD_DB_USER:-manyfold}:${MANYFOLD_DB_PASS}@${COMPOSE_PROJECT_NAME}-db/${COMPOSE_PROJECT_NAME}?pool=5
    volumes:
      - ${PROJECT_DATA_DIR:-${DATA_DIR:-/srv}/${COMPOSE_PROJECT_NAME}}:/libraries
    depends_on:
      manyfold-db:
        condition: service_healthy
      manyfold-kv:
        condition: service_healthy
    networks:
      - default
      - exposed
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3214"

  manyfold-db:
    extends:
      file: ../fragments/services.yml
      service: postgres
    environment:
      POSTGRES_USER: ${MANYFOLD_DB_USER:-manyfold}
      POSTGRES_PASSWORD: ${MANYFOLD_DB_PASS:?Manyfold DB password is missing}

  manyfold-kv:
    extends:
      file: ../fragments/services.yml
      service: valkey-persistent

networks:
  default:
    internal: true
  proxy:
    external: true
  exposed:
    external: true
